/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.FleetCatalog;
import Business.Business;
import Business.CustomerDirectory;
import java.awt.CardLayout;
import Business.AirlinerCatalog;

/**
 *
 * @author edmond
 */
public class TravelAgencyMain extends javax.swing.JFrame {
    private FleetCatalog fleetCatalog;
    private CustomerDirectory customerDirectory;
    private AirlinerCatalog airlinerCatalog;
    
    /**
     * Creates new form MainJFrame
     */
    public TravelAgencyMain() {
        initComponents();
        Business business = new Business();
        fleetCatalog = business.getfleetCatalog();
        customerDirectory = business.getCustomerDirectory();
        airlinerCatalog = business.getAirlinerCatalog();
        setSize(1500,1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JButton();
        btnAriliner = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(Container);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCustomer.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnCustomer.setText("Manager");
        btnCustomer.setActionCommand("place an order");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 52));

        btnAriliner.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnAriliner.setText("Airliner");
        btnAriliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArilinerActionPerformed(evt);
            }
        });
        jPanel2.add(btnAriliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 52));

        jSplitPane1.setLeftComponent(jPanel2);

        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 801, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        ManagerWorkArea mw = new ManagerWorkArea(Container, airlinerCatalog);
        Container.add("ManagerWorkArea", mw);
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.next(Container);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnArilinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArilinerActionPerformed
        // TODO add your handling code here:
        AirlinerLogin al = new AirlinerLogin(Container, airlinerCatalog);
        Container.add("AirlinerLogin", al);
        CardLayout layout = (CardLayout)Container.getLayout();
        layout.next(Container);
//        ManageFleet manageAirliner = new ManageFleet(Container,fleetCatalog);
//        Container.add("ManageAirliner",manageAirliner);
//        CardLayout layout = (CardLayout) Container.getLayout();
//        layout.next(Container);
    }//GEN-LAST:event_btnArilinerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelAgencyMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelAgencyMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton btnAriliner;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
