/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AirlinerRole;

import Business.Airliner;
import UserInterface.AirlinerRole.AddFleet;
import Business.Fleet;
import Business.FleetCatalog;
import Business.AirplaneCatalog;
import Business.Business;
import UserInterface.AirlinerRole.ManageAirplane;
import UserInterface.AirlinerRole.ViewFlightSchedule;
import UserInterface.TravelAgencyMain;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edmond
 */
public class ManageFleet extends javax.swing.JPanel {

    /**
     * Creates new form ManageFleet
     */
    private JPanel Container;
    private Airliner airliner;
    private AirplaneCatalog apc;
    
    public ManageFleet(JPanel c, Airliner a) {
        
        initComponents();       
        Container = c;       
        airliner = a;
        System.out.println("z:"+ airliner);        
        txtAirlinerName.setText(a.getAirlineName());
        refreshTable();
        
    }
    
    public void refreshProductTable(String keyword){
           DefaultTableModel model = (DefaultTableModel)tableFleet.getModel();
           model.setRowCount(0);

               for(Fleet a : airliner.getFleetCatalog().getFleetList()){
                   if( a.getFleetId() == Integer.parseInt(txtFleet.getText())){
                        Object row[] = new Object[2];
                        row[0] = a;
                        row[1] = a.getAirplaneCatalog().getAirplaneCatalog().size();
                        model.addRow(row);
                    }
               }
           }
    
    public void refreshTable(){

        DefaultTableModel model = (DefaultTableModel) tableFleet.getModel();
        model.setRowCount(0);


        for (Fleet f : airliner.getFleetCatalog().getFleetList()) {
            
            Object row[] = new Object[2];
            row[0] = f;
            row[1] = f.getAirplaneCatalog().getAirplaneCatalog().size();
            model.addRow(row);        }
    }
    
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFleet = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnViewPlane = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtFleet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        txtBack = new javax.swing.JButton();
        btnViewFleet = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText("Manage Fleets");

        tableFleet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fleet ID", "Airplane Numbers"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableFleet);

        btnRemove.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnCreate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnCreate.setText("Add New Fleet>>");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnViewPlane.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnViewPlane.setText("Manage Airplanes >>");
        btnViewPlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPlaneActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtFleet.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtFleet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFleetActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("Fleet Id:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("Airliner Name:");

        txtAirlinerName.setEditable(false);
        txtAirlinerName.setBackground(new java.awt.Color(204, 204, 204));
        txtAirlinerName.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtAirlinerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirlinerNameActionPerformed(evt);
            }
        });

        txtBack.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtBack.setText("<< Back");
        txtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBackActionPerformed(evt);
            }
        });

        btnViewFleet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewFleet.setText("View Fleet Details");
        btnViewFleet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFleetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtFleet, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch)
                        .addGap(183, 183, 183))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRemove)
                                        .addGap(273, 273, 273))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtBack)
                                        .addGap(324, 324, 324)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnViewFleet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewPlane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(151, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFleet, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnViewPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnViewFleet, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPlaneActionPerformed
        // TODO add your handling code here:
        int row = tableFleet.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Fleet s = (Fleet)tableFleet.getValueAt(row,0);
        
        ManageAirplane ma = new ManageAirplane(Container, s,apc);
        Container.add("ManageAirplane", ma);
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.next(Container);
     
    }//GEN-LAST:event_btnViewPlaneActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed

        int selectedRow = tableFleet.getSelectedRow();
        if(selectedRow>=0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to remove??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Fleet f = (Fleet) tableFleet.getValueAt(selectedRow, 0);
                airliner.getFleetCatalog().removeFleet(f);
                refreshTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
            
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
//         TODO add your handling code here:
        AddFleet createFleet = new AddFleet(Container,airliner);
        Container.add("CreateAirliner",createFleet);
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.next(Container);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtFleetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFleetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFleetActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String fleet = txtFleet.getText();
        refreshProductTable(fleet);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBackActionPerformed
        // TODO add your handling code here:
        Container.remove(this);
        CardLayout layout = (CardLayout) Container.getLayout();
        layout.previous(Container);
    }//GEN-LAST:event_txtBackActionPerformed

    private void btnViewFleetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFleetActionPerformed
        // TODO add your handling code here:   
        int selectedRow = tableFleet.getSelectedRow();

        if (selectedRow >= 0) 
        {
            Fleet f = (Fleet) tableFleet.getValueAt(selectedRow, 0);
            ViewFleet vf= new ViewFleet(Container,f);
            this.Container.add("ViewFleet", vf);
            CardLayout layout = (CardLayout) this.Container.getLayout();
            layout.next(Container);
            
        } 
        else 
        {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        }
        
    }//GEN-LAST:event_btnViewFleetActionPerformed

    private void txtAirlinerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirlinerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirlinerNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewFleet;
    private javax.swing.JButton btnViewPlane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFleet;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JButton txtBack;
    private javax.swing.JTextField txtFleet;
    // End of variables declaration//GEN-END:variables
}
