/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SchoolBusDriverRole;

//import UserInterface.Teacher.*;
//import UserInterface.Doctor.*;
//import UserInterface.SupermarkAdmin.*;
//import UserInterface.HospitalAdmin.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.KindergartenEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.BusOrganization;
import Business.UserAccount.UserAccount;
//import Business.Hospital.Ambulance;
//import Business.Hospital.Doctor;
//import Business.Hospital.Hospital;
//import Business.Hospital.Patient;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Unicorn
 */
public class SchoolBusDirverWorkJPanel extends javax.swing.JPanel implements Runnable{

    /**
     * Creates new form SysadminWorkArea
     */
    int hour, minute, second;
    
    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    UserAccount userAccount;
    BusOrganization busOrganization;
    KindergartenEnterprise kindergartenEnterprise;
    Network network;
    
//    private Hospital hospital;
//    private Doctor student;
//    private Ambulance schoolBus;
//    private Patient teacher;
    private String imagePath;
    public SchoolBusDirverWorkJPanel(JPanel userProcessContainer,UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAccount = account;
        this.busOrganization = (BusOrganization) organization;
        this.kindergartenEnterprise = (KindergartenEnterprise) enterprise;
        this.network = network;

        Thread t = new Thread(this);
        t.start();
        /*TableUI(TableNotification);
        TableUI(TableStudent);
        TableUI(tableWaitList);
        TableUI(TableDriver);
        TableUI(TablePatient);
        TableUI(TableComplaint);
        
        Dashboard.setVisible(true);
        Doctor.setVisible(false);
        Ambulance.setVisible(false);
        Patient.setVisible(false);
        SecurityRequest.setVisible(false);
        AmbulanceRequest.setVisible(false);
        ManageComplaint.setVisible(false);
        ManageInformation.setVisible(false);
        
        labelDoctorNum.setText(Integer.toString(hospital.getDoctorDirectory().getDoctorList().size()));
        labelDoctorNum.setFont(new Font("Tahoma", Font.BOLD, 36));
        labelDoctorNum.setOpaque(false);
        labelDoctorNum.setForeground(Color.WHITE);
        
        labelPatientNum.setText(Integer.toString(hospital.getPatientDirectory().getPatientList().size()));
        labelDoctorNum.setFont(new Font("Tahoma", Font.BOLD, 36));
        labelDoctorNum.setOpaque(false);
        labelDoctorNum.setForeground(Color.WHITE);
        
        labelComplaintNum.setText(Integer.toString(hospital.getComplaintDirectory().getComplaintList().size()));
        labelDoctorNum.setFont(new Font("Tahoma", Font.BOLD, 36));
        labelDoctorNum.setOpaque(false);
        labelDoctorNum.setForeground(Color.WHITE);
    }
    
    //pattern
    private boolean letterPattern(String a){
        Pattern p = Pattern.compile("[a-zA-Z]+");
        Matcher m = p.matcher(a);
        boolean b = m.matches();
        return b;
    }
    
    private boolean digitsPattern(String a){
        Pattern p = Pattern.compile("[0-9]+");
        Matcher m = p.matcher(a);
        boolean b = m.matches();
        return b;
    }
    
    
    public void TableUI(JTable table) {
        table.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 18));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(58, 83, 155));
        table.getTableHeader().setForeground(Color.BLACK); 
    */}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTime = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        btnInformation = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        labelComplaintNum1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        labelPatientNum1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        labelDoctorNum1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableNotification1 = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        btnMarkread1 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Student = new javax.swing.JPanel();
        txtViewStudent = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        btnViewStudent = new javax.swing.JButton();
        StudentJpanel = new javax.swing.JPanel();
        StudentNull = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        StudentDetails = new javax.swing.JPanel();
        txtStudentName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSentMessageToG = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtStudentGuardian = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtStudentAddress = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableStudent = new javax.swing.JTable();
        ManageComplaint = new javax.swing.JPanel();
        txtViewReceiver1 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        btnViewComplaint1 = new javax.swing.JButton();
        ComplaintJPanel = new javax.swing.JPanel();
        ComplaintNull = new javax.swing.JPanel();
        ComplaintInformation = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtComplaintDesc1 = new javax.swing.JTextArea();
        jLabel102 = new javax.swing.JLabel();
        sentMessageToAddresser1 = new javax.swing.JButton();
        txtComplaintReason1 = new javax.swing.JTextField();
        txtComAddresser1 = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        TableComplaint = new javax.swing.JTable();
        ManageInformation = new javax.swing.JPanel();
        image1 = new javax.swing.JLabel();
        btnphotoUpload1 = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        txtEntName1 = new javax.swing.JTextField();
        txtEntLocation1 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        txtPhoneNumber1 = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JTextField();
        jLabel81 = new javax.swing.JLabel();
        txtUserAccount1 = new javax.swing.JTextField();
        jLabel84 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        btnComplaint = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(58, 83, 155));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTime.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        labTime.setForeground(new java.awt.Color(255, 255, 255));
        labTime.setText("Time");
        add(labTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 1031, 291, 45));

        jButton6.setBackground(new java.awt.Color(58, 83, 155));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-double_left.png"))); // NOI18N
        jButton6.setText("Log out");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 35, 140, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hi,*** ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 48, -1, -1));

        btnDashboard.setBackground(new java.awt.Color(58, 83, 155));
        btnDashboard.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 240, 40));

        btnStudent.setBackground(new java.awt.Color(58, 83, 155));
        btnStudent.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnStudent.setText("Student List");
        btnStudent.setBorder(null);
        btnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 240, 40));

        btnInformation.setBackground(new java.awt.Color(58, 83, 155));
        btnInformation.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnInformation.setForeground(new java.awt.Color(255, 255, 255));
        btnInformation.setText("Manage Information");
        btnInformation.setBorder(null);
        btnInformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformationActionPerformed(evt);
            }
        });
        add(btnInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 240, 40));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-dashboard.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-registration.png"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 50, 60));

        ContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentPanel.setLayout(new java.awt.CardLayout());

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(58, 83, 155));

        labelComplaintNum1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelComplaintNum1.setForeground(new java.awt.Color(255, 255, 255));
        labelComplaintNum1.setText("0");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(labelComplaintNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(labelComplaintNum1)
                .addGap(30, 30, 30))
        );

        Dashboard.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 160, -1));

        jPanel11.setBackground(new java.awt.Color(58, 83, 155));

        labelPatientNum1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelPatientNum1.setForeground(new java.awt.Color(255, 255, 255));
        labelPatientNum1.setText("0");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(labelPatientNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(labelPatientNum1)
                .addGap(30, 30, 30))
        );

        Dashboard.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 160, -1));

        jPanel12.setBackground(new java.awt.Color(58, 83, 155));

        labelDoctorNum1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelDoctorNum1.setForeground(new java.awt.Color(255, 255, 255));
        labelDoctorNum1.setText("$200");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(labelDoctorNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(labelDoctorNum1)
                .addGap(29, 29, 29))
        );

        Dashboard.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, -1));

        TableNotification1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Addresser", "Content"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableNotification1.setFocusable(false);
        TableNotification1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableNotification1.setRowHeight(30);
        TableNotification1.setSelectionBackground(new java.awt.Color(68, 68, 147));
        TableNotification1.setShowVerticalLines(false);
        TableNotification1.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TableNotification1);

        Dashboard.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 630, 280));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(58, 83, 155));
        jLabel29.setText("Complaint Received");
        Dashboard.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 170, 30));

        btnMarkread1.setBackground(new java.awt.Color(255, 255, 255));
        btnMarkread1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnMarkread1.setForeground(new java.awt.Color(58, 83, 155));
        btnMarkread1.setText("Markread");
        btnMarkread1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        btnMarkread1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMarkread1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkread1ActionPerformed(evt);
            }
        });
        Dashboard.add(btnMarkread1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 750, 170, 40));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(58, 83, 155));
        jLabel30.setText("You have * new Notifications:");
        Dashboard.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 330, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(58, 83, 155));
        jLabel31.setText("Payments ");
        Dashboard.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 90, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(58, 83, 155));
        jLabel34.setText("Students Amount");
        Dashboard.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 150, 30));

        jLabel36.setBackground(new java.awt.Color(58, 83, 155));
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(58, 83, 155));
        jLabel36.setText("DASHBOARD");
        Dashboard.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        ContentPanel.add(Dashboard, "card5");

        Student.setBackground(new java.awt.Color(255, 255, 255));
        Student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtViewStudent.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewStudentActionPerformed(evt);
            }
        });
        Student.add(txtViewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 160, 30));

        jLabel52.setBackground(new java.awt.Color(58, 83, 155));
        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(58, 83, 155));
        jLabel52.setText("Student Directory");
        Student.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        btnViewStudent.setBackground(new java.awt.Color(255, 255, 255));
        btnViewStudent.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnViewStudent.setForeground(new java.awt.Color(58, 83, 155));
        btnViewStudent.setText("View");
        btnViewStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        btnViewStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewStudentActionPerformed(evt);
            }
        });
        Student.add(btnViewStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 120, 30));

        StudentJpanel.setBackground(new java.awt.Color(255, 255, 255));
        StudentJpanel.setLayout(new java.awt.CardLayout());

        StudentNull.setBackground(new java.awt.Color(255, 255, 255));
        StudentNull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-boy 3.png"))); // NOI18N
        StudentNull.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -10, 660, 550));

        StudentJpanel.add(StudentNull, "card5");

        StudentDetails.setBackground(new java.awt.Color(255, 255, 255));
        StudentDetails.setForeground(new java.awt.Color(255, 255, 255));
        StudentDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtStudentName.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });
        StudentDetails.add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 210, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(58, 83, 155));
        jLabel9.setText("Name:");
        StudentDetails.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 80, 30));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(58, 83, 155));
        jLabel11.setText("Sent Message to Guardian:");
        StudentDetails.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 270, 30));

        txtSentMessageToG.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtSentMessageToG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSentMessageToGActionPerformed(evt);
            }
        });
        StudentDetails.add(txtSentMessageToG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 370, 30));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(58, 83, 155));
        jLabel13.setText("Guardian:");
        StudentDetails.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 110, 30));

        txtStudentGuardian.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtStudentGuardian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentGuardianActionPerformed(evt);
            }
        });
        StudentDetails.add(txtStudentGuardian, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 210, 30));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(58, 83, 155));
        jButton3.setText("Sent");
        StudentDetails.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 130, 30));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(58, 83, 155));
        jLabel14.setText("Address:");
        StudentDetails.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 110, 30));

        txtStudentAddress.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtStudentAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentAddressActionPerformed(evt);
            }
        });
        StudentDetails.add(txtStudentAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 210, 30));

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(58, 83, 155));
        jButton4.setText("View Location");
        StudentDetails.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 140, 30));

        jLabel53.setBackground(new java.awt.Color(58, 83, 155));
        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(58, 83, 155));
        jLabel53.setText("Student Details Information");
        StudentDetails.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-boy 3.png"))); // NOI18N
        StudentDetails.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, -10, 660, 550));

        StudentJpanel.add(StudentDetails, "card3");

        Student.add(StudentJpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 940, 510));

        TableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Name", "Student ID", "Class", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableStudent.setFocusable(false);
        TableStudent.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableStudent.setRowHeight(30);
        TableStudent.setSelectionBackground(new java.awt.Color(68, 68, 147));
        TableStudent.setShowVerticalLines(false);
        TableStudent.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(TableStudent);

        Student.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 630, 280));

        ContentPanel.add(Student, "card4");

        ManageComplaint.setBackground(new java.awt.Color(255, 255, 255));
        ManageComplaint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtViewReceiver1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtViewReceiver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewReceiver1ActionPerformed(evt);
            }
        });
        ManageComplaint.add(txtViewReceiver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 160, 30));

        jLabel73.setBackground(new java.awt.Color(58, 83, 155));
        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(58, 83, 155));
        jLabel73.setText("Complaint Received");
        ManageComplaint.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btnViewComplaint1.setBackground(new java.awt.Color(255, 255, 255));
        btnViewComplaint1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnViewComplaint1.setForeground(new java.awt.Color(58, 83, 155));
        btnViewComplaint1.setText("View");
        btnViewComplaint1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        btnViewComplaint1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewComplaint1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewComplaint1ActionPerformed(evt);
            }
        });
        ManageComplaint.add(btnViewComplaint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 120, 30));

        ComplaintJPanel.setBackground(new java.awt.Color(255, 255, 255));
        ComplaintJPanel.setLayout(new java.awt.CardLayout());

        ComplaintNull.setBackground(new java.awt.Color(255, 255, 255));
        ComplaintNull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ComplaintJPanel.add(ComplaintNull, "card5");

        ComplaintInformation.setBackground(new java.awt.Color(255, 255, 255));
        ComplaintInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(58, 83, 155));
        jLabel95.setText("The detail information of Complaint");
        ComplaintInformation.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel96.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(58, 83, 155));
        jLabel96.setText("Complaint Reason:");
        ComplaintInformation.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, 30));

        jLabel100.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(58, 83, 155));
        jLabel100.setText("Description:");
        jLabel100.setToolTipText("");
        ComplaintInformation.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, 30));

        txtComplaintDesc1.setColumns(20);
        txtComplaintDesc1.setRows(5);
        jScrollPane10.setViewportView(txtComplaintDesc1);

        ComplaintInformation.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 530, 200));

        jLabel102.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(58, 83, 155));
        jLabel102.setText("Addresser:");
        jLabel102.setToolTipText("");
        ComplaintInformation.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 30));

        sentMessageToAddresser1.setBackground(new java.awt.Color(255, 255, 255));
        sentMessageToAddresser1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sentMessageToAddresser1.setForeground(new java.awt.Color(58, 83, 155));
        sentMessageToAddresser1.setText("Sent Message");
        sentMessageToAddresser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        sentMessageToAddresser1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sentMessageToAddresser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentMessageToAddresser1ActionPerformed(evt);
            }
        });
        ComplaintInformation.add(sentMessageToAddresser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 170, 30));

        txtComplaintReason1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtComplaintReason1.setToolTipText("");
        ComplaintInformation.add(txtComplaintReason1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 170, 30));

        txtComAddresser1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtComAddresser1.setToolTipText("");
        ComplaintInformation.add(txtComAddresser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 170, 30));

        ComplaintJPanel.add(ComplaintInformation, "card5");

        ManageComplaint.add(ComplaintJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 940, 510));

        TableComplaint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Complaint Reson", "Addresser"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableComplaint.setFocusable(false);
        TableComplaint.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableComplaint.setRowHeight(30);
        TableComplaint.setSelectionBackground(new java.awt.Color(68, 68, 147));
        TableComplaint.setShowVerticalLines(false);
        TableComplaint.getTableHeader().setReorderingAllowed(false);
        jScrollPane11.setViewportView(TableComplaint);

        ManageComplaint.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 630, 270));

        ContentPanel.add(ManageComplaint, "card4");

        ManageInformation.setBackground(new java.awt.Color(255, 255, 255));
        ManageInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image1.setForeground(new java.awt.Color(58, 83, 155));
        image1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profile photo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14), new java.awt.Color(58, 83, 155))); // NOI18N
        ManageInformation.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 210, 270));

        btnphotoUpload1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnphotoUpload1.setForeground(new java.awt.Color(58, 83, 155));
        btnphotoUpload1.setText("Upload");
        btnphotoUpload1.setEnabled(false);
        btnphotoUpload1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphotoUpload1ActionPerformed(evt);
            }
        });
        ManageInformation.add(btnphotoUpload1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 110, 40));

        btnUpdate1.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnUpdate1.setForeground(new java.awt.Color(58, 83, 155));
        btnUpdate1.setText("UPDATE");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        ManageInformation.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 810, 200, 40));

        btnSave1.setBackground(new java.awt.Color(255, 255, 255));
        btnSave1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnSave1.setForeground(new java.awt.Color(58, 83, 155));
        btnSave1.setText("SAVE");
        btnSave1.setEnabled(false);
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        ManageInformation.add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 810, 200, 40));

        jLabel78.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(58, 83, 155));
        jLabel78.setText("License plate:");
        jLabel78.setToolTipText("");
        ManageInformation.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, 30));

        txtEntName1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtEntName1.setForeground(new java.awt.Color(58, 83, 155));
        txtEntName1.setToolTipText("");
        txtEntName1.setEnabled(false);
        ManageInformation.add(txtEntName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 180, 30));

        txtEntLocation1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtEntLocation1.setForeground(new java.awt.Color(58, 83, 155));
        txtEntLocation1.setToolTipText("");
        txtEntLocation1.setEnabled(false);
        ManageInformation.add(txtEntLocation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 180, 30));

        jLabel79.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(58, 83, 155));
        jLabel79.setText("Model Number:");
        jLabel79.setToolTipText("");
        ManageInformation.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 140, 30));

        txtPhoneNumber1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtPhoneNumber1.setForeground(new java.awt.Color(58, 83, 155));
        txtPhoneNumber1.setToolTipText("");
        txtPhoneNumber1.setEnabled(false);
        ManageInformation.add(txtPhoneNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 180, 30));

        jLabel80.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(58, 83, 155));
        jLabel80.setText("Password:");
        jLabel80.setToolTipText("");
        ManageInformation.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 580, 80, 30));

        txtPassword1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtPassword1.setForeground(new java.awt.Color(58, 83, 155));
        txtPassword1.setToolTipText("");
        txtPassword1.setEnabled(false);
        ManageInformation.add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 180, 30));

        jLabel81.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(58, 83, 155));
        jLabel81.setText("User Account:");
        jLabel81.setToolTipText("");
        ManageInformation.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 110, 30));

        txtUserAccount1.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtUserAccount1.setForeground(new java.awt.Color(58, 83, 155));
        txtUserAccount1.setToolTipText("");
        txtUserAccount1.setEnabled(false);
        ManageInformation.add(txtUserAccount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 490, 180, 30));

        jLabel84.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(58, 83, 155));
        jLabel84.setText("Persons capacity:");
        jLabel84.setToolTipText("");
        ManageInformation.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 150, 30));

        jLabel87.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-profile.png"))); // NOI18N
        ManageInformation.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 680, 670));

        jLabel88.setBackground(new java.awt.Color(58, 83, 155));
        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(58, 83, 155));
        jLabel88.setText("Manage Information");
        ManageInformation.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        ContentPanel.add(ManageInformation, "card8");

        add(ContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 128, -1, 954));

        btnComplaint.setBackground(new java.awt.Color(58, 83, 155));
        btnComplaint.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnComplaint.setForeground(new java.awt.Color(255, 255, 255));
        btnComplaint.setText("Complaint Received");
        btnComplaint.setBorder(null);
        btnComplaint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplaintActionPerformed(evt);
            }
        });
        add(btnComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 240, 40));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-strike.png"))); // NOI18N
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 40));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-student_male.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(true);
        
        ManageInformation.setVisible(false);
        
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        
        ManageInformation.setVisible(false);
        /*
        //SubJPanel
        DoctorNull.setVisible(true);
        StudentWaitList.setVisible(false);
        DoctorInformation.setVisible(false);
        
        //first-in
        refreshStudentTable();*/
    }//GEN-LAST:event_btnStudentActionPerformed

   /* public void refreshStudentTable(){
        DefaultTableModel model = (DefaultTableModel) TableStudent.getModel();
        model.setRowCount(0);
        for(Student a: kindergarden.getStudentDirectory().getStudentList()){
            Object row[] = new Object[3];
            row[0] = a;
            row[1] = a.getId();
            row[2] = a.getClassname();
            model.addRow(row);
        }
    }*/
    
    private void btnInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformationActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        
        ManageInformation.setVisible(false);
        
        /*txtEntName.setText(kindergarden.getName());
        txtEntLocation.setText(kindergarden.getName());
        txtPhoneNumber.setText(kindergarden.getName());
        txtEntName.setText(kindergarden.getName());
        comboStatus.setSelectedItem(kindergarden.getStatus());
        comboxOpenTime.setSelectedItem(kindergarden.getOpenTime());
        comboxClosedTime.setSelectedItem(kindergarden.getClosedTime());*/
    }//GEN-LAST:event_btnInformationActionPerformed
    
    public void refreshTeacherTable(){
    }    
    private void btnComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnComplaintActionPerformed

    private void btnMarkread1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkread1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnMarkread1ActionPerformed

    private void txtViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewStudentActionPerformed

    private void btnViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewStudentActionPerformed
        // TODO add your handling code here:
        /*int selectedRow = TableDriver.getSelectedRow();

        if (selectedRow >= 0)
        {
            SchoolBus s = (SchoolBus) TablePatient.getValueAt(selectedRow, 0);
            //setvisable
            PatientNull.setVisible(false);
            SchoolBusAdd.setVisible(false);
            PatientViewInformation.setVisible(true);

            //txt
            vPatientName.setText(s.getLicense());
            vPatientPhone.setText(s.getModelNum());
            vPatientTypeofillness.setText(s.getPersonCapacity());
            vYear.setText(s.getManfacturedYear());

            //
            schoolBus = s;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a school bus.");
        }*/
    }//GEN-LAST:event_btnViewStudentActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void txtSentMessageToGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSentMessageToGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSentMessageToGActionPerformed

    private void txtStudentGuardianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentGuardianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentGuardianActionPerformed

    private void txtStudentAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentAddressActionPerformed

    private void txtViewReceiver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewReceiver1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewReceiver1ActionPerformed

    private void btnViewComplaint1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewComplaint1ActionPerformed
        // TODO add your handling code here:
        /*int selectedRow = TableComplaint.getSelectedRow();

        if (selectedRow >= 0)
        {
            Complaint s = (Complaint) TableComplaint.getValueAt(selectedRow, 0);
            //setvisable
            ComplaintNull.setVisible(false);
            ComplaintInformation.setVisible(true);

            //txt
            txtComAddresser.setText(s.getAddresser());
            txtComplaintEmployee.setText(s.getReceiver());
            txtComplaintReason.setText(s.getComplaintReason());
            txtComplaintDesc.setText(s.getDesc());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a school bus.");
        }*/
    }//GEN-LAST:event_btnViewComplaint1ActionPerformed

    private void sentMessageToAddresser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentMessageToAddresser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sentMessageToAddresser1ActionPerformed

    private void btnphotoUpload1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphotoUpload1ActionPerformed
        // TODO add your handling code here:
        /*JFileChooser upload = new JFileChooser();
        upload.showOpenDialog(null);
        File file = upload.getSelectedFile();
        String path = file.getAbsolutePath();
        imagePath = path;

        Image im = Toolkit.getDefaultToolkit().createImage(path);
        im = im.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ima = new ImageIcon(im);
        kindergarden.setMyimage(ima);
        image.setIcon(ima);*/
    }//GEN-LAST:event_btnphotoUpload1ActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:

        /*txtEntName.setText(kindergarden.getName());
        txtEntLocation.setText(kindergarden.getName());
        txtPhoneNumber.setText(kindergarden.getName());
        txtEntName.setText(kindergarden.getName());
        comboStatus.setSelectedItem(kindergarden.getStatus());
        comboxOpenTime.setSelectedItem(kindergarden.getOpenTime());
        comboxClosedTime.setSelectedItem(kindergarden.getClosedTime());*/
    }//GEN-LAST:event_btnSave1ActionPerformed
    
    @Override
    public void run() {
        while (true) {            
            Calendar cal = Calendar.getInstance();
            hour = cal.get(Calendar.HOUR_OF_DAY);
            minute = cal.get(Calendar.MINUTE);
            second = cal.get(Calendar.SECOND);
            
            SimpleDateFormat sdftime = new SimpleDateFormat("yyyy-MM-dd  hh:mm:ss");
            Date date = cal.getTime();
            String timeForm = sdftime.format(date);
            labTime.setText(timeForm);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ComplaintInformation;
    private javax.swing.JPanel ComplaintJPanel;
    private javax.swing.JPanel ComplaintNull;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel ManageComplaint;
    private javax.swing.JPanel ManageInformation;
    private javax.swing.JPanel Student;
    private javax.swing.JPanel StudentDetails;
    private javax.swing.JPanel StudentJpanel;
    private javax.swing.JPanel StudentNull;
    private javax.swing.JTable TableComplaint;
    private javax.swing.JTable TableNotification1;
    private javax.swing.JTable TableStudent;
    private javax.swing.JButton btnComplaint;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnInformation;
    private javax.swing.JButton btnMarkread1;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnViewComplaint1;
    private javax.swing.JButton btnViewStudent;
    private javax.swing.JButton btnphotoUpload1;
    private javax.swing.JLabel image1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labTime;
    private javax.swing.JLabel labelComplaintNum1;
    private javax.swing.JLabel labelDoctorNum1;
    private javax.swing.JLabel labelPatientNum1;
    private javax.swing.JButton sentMessageToAddresser1;
    private javax.swing.JTextField txtComAddresser1;
    private javax.swing.JTextArea txtComplaintDesc1;
    private javax.swing.JTextField txtComplaintReason1;
    private javax.swing.JTextField txtEntLocation1;
    private javax.swing.JTextField txtEntName1;
    private javax.swing.JTextField txtPassword1;
    private javax.swing.JTextField txtPhoneNumber1;
    private javax.swing.JTextField txtSentMessageToG;
    private javax.swing.JTextField txtStudentAddress;
    private javax.swing.JTextField txtStudentGuardian;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtUserAccount1;
    private javax.swing.JTextField txtViewReceiver1;
    private javax.swing.JTextField txtViewStudent;
    // End of variables declaration//GEN-END:variables
}
