/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

//import UserInterface.SupermarkAdmin.*;
//import UserInterface.HospitalAdmin.*;
import Business.EcoSystem;
//import Business.Hospital.Ambulance;
//import Business.Hospital.Doctor;
//import Business.Hospital.Hospital;
//import Business.Hospital.Patient;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Unicorn
 */
public class DoctorWorkJpanel extends javax.swing.JPanel implements Runnable{

    /**
     * Creates new form SysadminWorkArea
     */
    int hour, minute, second;
    
    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    
//    private Hospital hospital;
//    private Doctor student;
//    private Ambulance schoolBus;
//    private Patient teacher;
    private String imagePath;
    public DoctorWorkJpanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;

        Thread t = new Thread(this);
        t.start();
        /*TableUI(TableNotification);
        TableUI(TableStudent);
        TableUI(tableWaitList);
        TableUI(TableDriver);
        TableUI(TablePatient);
        TableUI(TableComplaint);
        
        Dashboard.setVisible(true);
        Doctor.setVisible(false);
        Ambulance.setVisible(false);
        Patient.setVisible(false);
        SecurityRequest.setVisible(false);
        AmbulanceRequest.setVisible(false);
        ManageComplaint.setVisible(false);
        ManageInformation.setVisible(false);
        
        labelDoctorNum.setText(Integer.toString(hospital.getDoctorDirectory().getDoctorList().size()));
        labelDoctorNum.setFont(new Font("Tahoma", Font.BOLD, 36));
        labelDoctorNum.setOpaque(false);
        labelDoctorNum.setForeground(Color.WHITE);
        
        labelPatientNum.setText(Integer.toString(hospital.getPatientDirectory().getPatientList().size()));
        labelDoctorNum.setFont(new Font("Tahoma", Font.BOLD, 36));
        labelDoctorNum.setOpaque(false);
        labelDoctorNum.setForeground(Color.WHITE);
        
        labelComplaintNum.setText(Integer.toString(hospital.getComplaintDirectory().getComplaintList().size()));
        labelDoctorNum.setFont(new Font("Tahoma", Font.BOLD, 36));
        labelDoctorNum.setOpaque(false);
        labelDoctorNum.setForeground(Color.WHITE);
    }
    
    //pattern
    private boolean letterPattern(String a){
        Pattern p = Pattern.compile("[a-zA-Z]+");
        Matcher m = p.matcher(a);
        boolean b = m.matches();
        return b;
    }
    
    private boolean digitsPattern(String a){
        Pattern p = Pattern.compile("[0-9]+");
        Matcher m = p.matcher(a);
        boolean b = m.matches();
        return b;
    }
    
    
    public void TableUI(JTable table) {
        table.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 18));
        table.getTableHeader().setOpaque(false);
        table.getTableHeader().setBackground(new Color(58, 83, 155));
        table.getTableHeader().setForeground(Color.BLACK); 
    */}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labTime = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnMyPatient = new javax.swing.JButton();
        btnInformation = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        labelComplaintNum = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        labelPatientNum = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        labelDoctorNum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNotification = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        btnMarkread = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Patient = new javax.swing.JPanel();
        txtViewBus1 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        btnViewBus1 = new javax.swing.JButton();
        PatientJPanel = new javax.swing.JPanel();
        PatientNull = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PatientViewInformation = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        btnPatientUpload = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        vPatientTypeofillness = new javax.swing.JTextField();
        vPatientPhone = new javax.swing.JTextField();
        vPatientName = new javax.swing.JTextField();
        btnPatientSave = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        vcomboxDegree = new javax.swing.JComboBox<>();
        vAdmissionTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablePatient = new javax.swing.JTable();
        IncidentReport = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TxtAreaDescription = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TxtAreaExplanation = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnLocation = new javax.swing.JButton();
        ManageComplaint = new javax.swing.JPanel();
        txtViewReceiver = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        btnViewComplaint = new javax.swing.JButton();
        ComplaintJPanel = new javax.swing.JPanel();
        ComplaintNull = new javax.swing.JPanel();
        ComplaintInformation = new javax.swing.JPanel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtComplaintDesc = new javax.swing.JTextArea();
        jLabel101 = new javax.swing.JLabel();
        sentMessageToAddresser = new javax.swing.JButton();
        txtComplaintReason = new javax.swing.JTextField();
        txtComAddresser = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        TableComplaint = new javax.swing.JTable();
        ManageInformation = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        btnphotoUpload = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel71 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        txtUserAccount = new javax.swing.JTextField();
        txtPosition = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnComplaint = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(58, 83, 155));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labTime.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        labTime.setForeground(new java.awt.Color(255, 255, 255));
        labTime.setText("Time");
        add(labTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 1031, 291, 45));

        jButton6.setBackground(new java.awt.Color(58, 83, 155));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-double_left.png"))); // NOI18N
        jButton6.setText("Log out");
        jButton6.setBorder(null);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 35, 140, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hi,*** ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 48, -1, -1));

        btnDashboard.setBackground(new java.awt.Color(58, 83, 155));
        btnDashboard.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 240, 40));

        btnMyPatient.setBackground(new java.awt.Color(58, 83, 155));
        btnMyPatient.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnMyPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnMyPatient.setText("My Patient");
        btnMyPatient.setBorder(null);
        btnMyPatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMyPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyPatientActionPerformed(evt);
            }
        });
        add(btnMyPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 240, 40));

        btnInformation.setBackground(new java.awt.Color(58, 83, 155));
        btnInformation.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnInformation.setForeground(new java.awt.Color(255, 255, 255));
        btnInformation.setText("Manage Information");
        btnInformation.setBorder(null);
        btnInformation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformationActionPerformed(evt);
            }
        });
        add(btnInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 240, 40));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-dashboard.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-registration.png"))); // NOI18N
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 50, 60));

        ContentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ContentPanel.setLayout(new java.awt.CardLayout());

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(58, 83, 155));

        labelComplaintNum.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelComplaintNum.setForeground(new java.awt.Color(255, 255, 255));
        labelComplaintNum.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(labelComplaintNum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(labelComplaintNum)
                .addGap(30, 30, 30))
        );

        Dashboard.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 160, -1));

        jPanel8.setBackground(new java.awt.Color(58, 83, 155));

        labelPatientNum.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelPatientNum.setForeground(new java.awt.Color(255, 255, 255));
        labelPatientNum.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(labelPatientNum, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(labelPatientNum)
                .addGap(30, 30, 30))
        );

        Dashboard.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 160, -1));

        jPanel9.setBackground(new java.awt.Color(58, 83, 155));

        labelDoctorNum.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelDoctorNum.setForeground(new java.awt.Color(255, 255, 255));
        labelDoctorNum.setText("$200");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(labelDoctorNum, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(labelDoctorNum)
                .addGap(29, 29, 29))
        );

        Dashboard.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 160, -1));

        TableNotification.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Addresser", "Content"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableNotification.setFocusable(false);
        TableNotification.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableNotification.setRowHeight(30);
        TableNotification.setSelectionBackground(new java.awt.Color(68, 68, 147));
        TableNotification.setShowVerticalLines(false);
        TableNotification.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableNotification);

        Dashboard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 630, 280));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(58, 83, 155));
        jLabel26.setText("Complaint Received");
        Dashboard.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 170, 30));

        btnMarkread.setBackground(new java.awt.Color(255, 255, 255));
        btnMarkread.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnMarkread.setForeground(new java.awt.Color(58, 83, 155));
        btnMarkread.setText("Markread");
        btnMarkread.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        btnMarkread.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMarkread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkreadActionPerformed(evt);
            }
        });
        Dashboard.add(btnMarkread, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 750, 170, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(58, 83, 155));
        jLabel27.setText("You have * new Notifications:");
        Dashboard.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 330, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(58, 83, 155));
        jLabel28.setText("Payments ");
        Dashboard.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 90, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(58, 83, 155));
        jLabel33.setText("Patients Amount");
        Dashboard.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, 30));

        jLabel35.setBackground(new java.awt.Color(58, 83, 155));
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(58, 83, 155));
        jLabel35.setText("DASHBOARD");
        Dashboard.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        ContentPanel.add(Dashboard, "card5");

        Patient.setBackground(new java.awt.Color(255, 255, 255));
        Patient.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtViewBus1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtViewBus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewBus1ActionPerformed(evt);
            }
        });
        Patient.add(txtViewBus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 160, 30));

        jLabel50.setBackground(new java.awt.Color(58, 83, 155));
        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(58, 83, 155));
        jLabel50.setText("Patient Directory");
        Patient.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        btnViewBus1.setBackground(new java.awt.Color(255, 255, 255));
        btnViewBus1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnViewBus1.setForeground(new java.awt.Color(58, 83, 155));
        btnViewBus1.setText("View");
        btnViewBus1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        btnViewBus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewBus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBus1ActionPerformed(evt);
            }
        });
        Patient.add(btnViewBus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 120, 30));

        PatientJPanel.setBackground(new java.awt.Color(255, 255, 255));
        PatientJPanel.setLayout(new java.awt.CardLayout());

        PatientNull.setBackground(new java.awt.Color(255, 255, 255));
        PatientNull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-patient_care.png"))); // NOI18N
        PatientNull.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 590, 470));

        PatientJPanel.add(PatientNull, "card5");

        PatientViewInformation.setBackground(new java.awt.Color(255, 255, 255));
        PatientViewInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(58, 83, 155));
        jLabel51.setText("The detail information of Patient");
        PatientViewInformation.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(58, 83, 155));
        jLabel52.setText("Name:");
        PatientViewInformation.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, 30));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(58, 83, 155));
        jLabel53.setText("Phone Number:");
        jLabel53.setToolTipText("");
        PatientViewInformation.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 30));

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(58, 83, 155));
        jLabel54.setText("Type of illness:");
        jLabel54.setToolTipText("");
        PatientViewInformation.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 130, 30));

        btnPatientUpload.setBackground(new java.awt.Color(255, 255, 255));
        btnPatientUpload.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPatientUpload.setForeground(new java.awt.Color(58, 83, 155));
        btnPatientUpload.setText("Upload");
        btnPatientUpload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        btnPatientUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPatientUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientUploadActionPerformed(evt);
            }
        });
        PatientViewInformation.add(btnPatientUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 130, 40));

        jLabel57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(58, 83, 155));
        jLabel57.setText("Admission time:");
        jLabel57.setToolTipText("");
        PatientViewInformation.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, 30));

        vPatientTypeofillness.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        vPatientTypeofillness.setToolTipText("");
        vPatientTypeofillness.setEnabled(false);
        PatientViewInformation.add(vPatientTypeofillness, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 180, 30));

        vPatientPhone.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        vPatientPhone.setToolTipText("");
        vPatientPhone.setEnabled(false);
        vPatientPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vPatientPhoneActionPerformed(evt);
            }
        });
        PatientViewInformation.add(vPatientPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 180, 30));

        vPatientName.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        vPatientName.setToolTipText("");
        vPatientName.setEnabled(false);
        PatientViewInformation.add(vPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 180, 30));

        btnPatientSave.setBackground(new java.awt.Color(255, 255, 255));
        btnPatientSave.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPatientSave.setForeground(new java.awt.Color(58, 83, 155));
        btnPatientSave.setText("Save");
        btnPatientSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        btnPatientSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPatientSave.setEnabled(false);
        btnPatientSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientSaveActionPerformed(evt);
            }
        });
        PatientViewInformation.add(btnPatientSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 130, 40));

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(58, 83, 155));
        jLabel58.setText("Degree of illness:");
        jLabel58.setToolTipText("");
        PatientViewInformation.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, 30));

        vcomboxDegree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vcomboxDegree.setEnabled(false);
        PatientViewInformation.add(vcomboxDegree, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 180, 40));

        vAdmissionTime.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        vAdmissionTime.setToolTipText("");
        vAdmissionTime.setEnabled(false);
        PatientViewInformation.add(vAdmissionTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 180, 30));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-patient_care.png"))); // NOI18N
        PatientViewInformation.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 590, 470));

        PatientJPanel.add(PatientViewInformation, "card5");

        Patient.add(PatientJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 940, 510));

        TablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient Name", "Type of illness", "Degree of illness"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablePatient.setFocusable(false);
        TablePatient.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TablePatient.setRowHeight(30);
        TablePatient.setSelectionBackground(new java.awt.Color(68, 68, 147));
        TablePatient.setShowVerticalLines(false);
        TablePatient.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TablePatient);
        if (TablePatient.getColumnModel().getColumnCount() > 0) {
            TablePatient.getColumnModel().getColumn(0).setResizable(false);
            TablePatient.getColumnModel().getColumn(1).setResizable(false);
            TablePatient.getColumnModel().getColumn(2).setResizable(false);
        }

        Patient.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 630, 250));

        ContentPanel.add(Patient, "card4");

        IncidentReport.setBackground(new java.awt.Color(255, 255, 255));
        IncidentReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(19, 19, 114));

        jLabel14.setBackground(new java.awt.Color(2, 2, 69));
        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Incident Report");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel14)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        IncidentReport.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 980, 70));

        TxtAreaDescription.setColumns(20);
        TxtAreaDescription.setRows(5);
        jScrollPane4.setViewportView(TxtAreaDescription);

        IncidentReport.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 530, 140));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 2, 69));
        jLabel15.setText("Location:");
        jLabel15.setToolTipText("");
        IncidentReport.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, 30));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(2, 2, 69));
        jLabel16.setText("Description of Incident:");
        jLabel16.setToolTipText("");
        IncidentReport.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, 30));

        txtType.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtType.setForeground(new java.awt.Color(2, 2, 69));
        txtType.setToolTipText("");
        IncidentReport.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 180, 30));

        txtLocation.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtLocation.setForeground(new java.awt.Color(2, 2, 69));
        txtLocation.setToolTipText("");
        IncidentReport.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 180, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(2, 2, 69));
        jLabel18.setText("Incident type:");
        jLabel18.setToolTipText("");
        IncidentReport.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, 30));

        TxtAreaExplanation.setColumns(20);
        TxtAreaExplanation.setRows(5);
        jScrollPane12.setViewportView(TxtAreaExplanation);

        IncidentReport.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 530, 150));

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(2, 2, 69));
        jLabel25.setText("Exployee Explanation:");
        jLabel25.setToolTipText("");
        IncidentReport.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, 30));

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(2, 2, 69));
        btnSubmit.setText("SUBMIT");
        IncidentReport.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 800, 200, 40));

        btnLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-user_location.png"))); // NOI18N
        btnLocation.setBorder(null);
        IncidentReport.add(btnLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 80, 30));

        ContentPanel.add(IncidentReport, "card11");

        ManageComplaint.setBackground(new java.awt.Color(255, 255, 255));
        ManageComplaint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtViewReceiver.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        txtViewReceiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewReceiverActionPerformed(evt);
            }
        });
        ManageComplaint.add(txtViewReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 160, 30));

        jLabel70.setBackground(new java.awt.Color(58, 83, 155));
        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(58, 83, 155));
        jLabel70.setText("Complaint Received");
        ManageComplaint.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btnViewComplaint.setBackground(new java.awt.Color(255, 255, 255));
        btnViewComplaint.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnViewComplaint.setForeground(new java.awt.Color(58, 83, 155));
        btnViewComplaint.setText("View");
        btnViewComplaint.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        btnViewComplaint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewComplaintActionPerformed(evt);
            }
        });
        ManageComplaint.add(btnViewComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 120, 30));

        ComplaintJPanel.setBackground(new java.awt.Color(255, 255, 255));
        ComplaintJPanel.setLayout(new java.awt.CardLayout());

        ComplaintNull.setBackground(new java.awt.Color(255, 255, 255));
        ComplaintNull.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ComplaintJPanel.add(ComplaintNull, "card5");

        ComplaintInformation.setBackground(new java.awt.Color(255, 255, 255));
        ComplaintInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(58, 83, 155));
        jLabel93.setText("The detail information of Complaint");
        ComplaintInformation.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel94.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(58, 83, 155));
        jLabel94.setText("Complaint Reason:");
        ComplaintInformation.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, 30));

        jLabel99.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(58, 83, 155));
        jLabel99.setText("Description:");
        jLabel99.setToolTipText("");
        ComplaintInformation.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, 30));

        txtComplaintDesc.setColumns(20);
        txtComplaintDesc.setRows(5);
        jScrollPane9.setViewportView(txtComplaintDesc);

        ComplaintInformation.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 530, 200));

        jLabel101.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(58, 83, 155));
        jLabel101.setText("Addresser:");
        jLabel101.setToolTipText("");
        ComplaintInformation.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 30));

        sentMessageToAddresser.setBackground(new java.awt.Color(255, 255, 255));
        sentMessageToAddresser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sentMessageToAddresser.setForeground(new java.awt.Color(58, 83, 155));
        sentMessageToAddresser.setText("Sent Message");
        sentMessageToAddresser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(58, 83, 155)));
        sentMessageToAddresser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sentMessageToAddresser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sentMessageToAddresserActionPerformed(evt);
            }
        });
        ComplaintInformation.add(sentMessageToAddresser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 170, 30));

        txtComplaintReason.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtComplaintReason.setToolTipText("");
        ComplaintInformation.add(txtComplaintReason, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 170, 30));

        txtComAddresser.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtComAddresser.setToolTipText("");
        ComplaintInformation.add(txtComAddresser, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 170, 30));

        ComplaintJPanel.add(ComplaintInformation, "card5");

        ManageComplaint.add(ComplaintJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 940, 510));

        TableComplaint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Complaint Reson", "Addresser"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableComplaint.setFocusable(false);
        TableComplaint.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableComplaint.setRowHeight(30);
        TableComplaint.setSelectionBackground(new java.awt.Color(68, 68, 147));
        TableComplaint.setShowVerticalLines(false);
        TableComplaint.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(TableComplaint);
        if (TableComplaint.getColumnModel().getColumnCount() > 0) {
            TableComplaint.getColumnModel().getColumn(0).setResizable(false);
            TableComplaint.getColumnModel().getColumn(1).setResizable(false);
        }

        ManageComplaint.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 630, 250));

        ContentPanel.add(ManageComplaint, "card4");

        ManageInformation.setBackground(new java.awt.Color(255, 255, 255));
        ManageInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image.setForeground(new java.awt.Color(58, 83, 155));
        image.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profile photo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14), new java.awt.Color(58, 83, 155))); // NOI18N
        ManageInformation.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 210, 270));

        btnphotoUpload.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnphotoUpload.setForeground(new java.awt.Color(58, 83, 155));
        btnphotoUpload.setText("Upload");
        btnphotoUpload.setEnabled(false);
        btnphotoUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphotoUploadActionPerformed(evt);
            }
        });
        ManageInformation.add(btnphotoUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 110, 40));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(58, 83, 155));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        ManageInformation.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 810, 200, 40));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(58, 83, 155));
        btnSave.setText("SAVE");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        ManageInformation.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 810, 200, 40));

        jLabel71.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(58, 83, 155));
        jLabel71.setText(" Name:");
        jLabel71.setToolTipText("");
        ManageInformation.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, 30));

        txtName.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtName.setForeground(new java.awt.Color(58, 83, 155));
        txtName.setToolTipText("");
        txtName.setEnabled(false);
        ManageInformation.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 180, 30));

        txtEmail.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(58, 83, 155));
        txtEmail.setToolTipText("");
        txtEmail.setEnabled(false);
        ManageInformation.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 180, 30));

        jLabel72.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(58, 83, 155));
        jLabel72.setText("E-mails:");
        jLabel72.setToolTipText("");
        ManageInformation.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 90, 30));

        txtDepartment.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtDepartment.setForeground(new java.awt.Color(58, 83, 155));
        txtDepartment.setToolTipText("");
        txtDepartment.setEnabled(false);
        ManageInformation.add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 180, 30));

        jLabel74.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(58, 83, 155));
        jLabel74.setText("Position:");
        jLabel74.setToolTipText("");
        ManageInformation.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 70, 30));

        jLabel75.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(58, 83, 155));
        jLabel75.setText("Password:");
        jLabel75.setToolTipText("");
        ManageInformation.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, 90, 30));

        txtPassword.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(58, 83, 155));
        txtPassword.setToolTipText("");
        txtPassword.setEnabled(false);
        ManageInformation.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 180, 30));

        jLabel76.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(58, 83, 155));
        jLabel76.setText("User Account:");
        jLabel76.setToolTipText("");
        ManageInformation.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 120, 30));

        txtUserAccount.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtUserAccount.setForeground(new java.awt.Color(58, 83, 155));
        txtUserAccount.setToolTipText("");
        txtUserAccount.setEnabled(false);
        ManageInformation.add(txtUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, 180, 30));

        txtPosition.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtPosition.setForeground(new java.awt.Color(58, 83, 155));
        txtPosition.setToolTipText("");
        txtPosition.setEnabled(false);
        ManageInformation.add(txtPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 180, 30));

        txtPhoneNumber.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(58, 83, 155));
        txtPhoneNumber.setToolTipText("");
        txtPhoneNumber.setEnabled(false);
        ManageInformation.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 180, 30));

        jLabel77.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(58, 83, 155));
        jLabel77.setText("Department:");
        jLabel77.setToolTipText("");
        ManageInformation.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 100, 30));

        jLabel83.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(58, 83, 155));
        jLabel83.setText("Phone Number:");
        jLabel83.setToolTipText("");
        ManageInformation.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 140, 30));

        jLabel85.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-profile.png"))); // NOI18N
        ManageInformation.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 680, 670));

        jLabel86.setBackground(new java.awt.Color(58, 83, 155));
        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(58, 83, 155));
        jLabel86.setText("Manage Information");
        ManageInformation.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        ContentPanel.add(ManageInformation, "card8");

        add(ContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 128, -1, 954));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-cast.png"))); // NOI18N
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 60));

        btnComplaint.setBackground(new java.awt.Color(58, 83, 155));
        btnComplaint.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btnComplaint.setForeground(new java.awt.Color(255, 255, 255));
        btnComplaint.setText("Complaint Received");
        btnComplaint.setBorder(null);
        btnComplaint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplaintActionPerformed(evt);
            }
        });
        add(btnComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 240, 40));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/images/icons8-strike.png"))); // NOI18N
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(true);
        
        ManageInformation.setVisible(false);
        
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnMyPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyPatientActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        
        ManageInformation.setVisible(false);
        /*
        //SubJPanel
        DoctorNull.setVisible(true);
        StudentWaitList.setVisible(false);
        DoctorInformation.setVisible(false);
        
        //first-in
        refreshStudentTable();*/
    }//GEN-LAST:event_btnMyPatientActionPerformed

   /* public void refreshStudentTable(){
        DefaultTableModel model = (DefaultTableModel) TableStudent.getModel();
        model.setRowCount(0);
        for(Student a: kindergarden.getStudentDirectory().getStudentList()){
            Object row[] = new Object[3];
            row[0] = a;
            row[1] = a.getId();
            row[2] = a.getClassname();
            model.addRow(row);
        }
    }*/
    
    private void btnInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformationActionPerformed
        // TODO add your handling code here:
        Dashboard.setVisible(false);
        
        ManageInformation.setVisible(false);
        
        /*txtEntName.setText(kindergarden.getName());
        txtEntLocation.setText(kindergarden.getName());
        txtPhoneNumber.setText(kindergarden.getName());
        txtEntName.setText(kindergarden.getName());
        comboStatus.setSelectedItem(kindergarden.getStatus());
        comboxOpenTime.setSelectedItem(kindergarden.getOpenTime());
        comboxClosedTime.setSelectedItem(kindergarden.getClosedTime());*/
    }//GEN-LAST:event_btnInformationActionPerformed
    
    public void refreshTeacherTable(){
    }    
    private void btnMarkreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkreadActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnMarkreadActionPerformed

    private void txtViewBus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewBus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewBus1ActionPerformed

    private void btnViewBus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBus1ActionPerformed
        // TODO add your handling code here:
        /*int selectedRow = TableDriver.getSelectedRow();

        if (selectedRow >= 0)
        {
            SchoolBus s = (SchoolBus) TablePatient.getValueAt(selectedRow, 0);
            //setvisable
            PatientNull.setVisible(false);
            SchoolBusAdd.setVisible(false);
            PatientViewInformation.setVisible(true);

            //txt
            vPatientName.setText(s.getLicense());
            vPatientPhone.setText(s.getModelNum());
            vPatientTypeofillness.setText(s.getPersonCapacity());
            vYear.setText(s.getManfacturedYear());

            //
            schoolBus = s;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a school bus.");
        }*/
    }//GEN-LAST:event_btnViewBus1ActionPerformed

    private void btnPatientUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientUploadActionPerformed
        // TODO add your handling code here:
        vPatientName.setEnabled(true);
        vPatientPhone.setEnabled(true);
        vPatientTypeofillness.setEnabled(true);
        
        btnPatientSave.setEnabled(true);
        btnPatientUpload.setEnabled(false);
    }//GEN-LAST:event_btnPatientUploadActionPerformed

    private void vPatientPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vPatientPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vPatientPhoneActionPerformed

    private void btnPatientSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientSaveActionPerformed
        // TODO add your handling code here:
  
        /*refreshBusTable();

        vPatientName.setEnabled(false);
        vPatientPhone.setEnabled(false);
        vPatientTypeofillness.setEnabled(false);
        vYear.setEnabled(false);
        vAmbulanceUserName.setEnabled(false);
        vAmbulancePassword.setEnabled(false);
        btnPatientSave.setEnabled(false);
        btnPatientUpload.setEnabled(true);*/
    }//GEN-LAST:event_btnPatientSaveActionPerformed

    private void btnComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplaintActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnComplaintActionPerformed

    private void txtViewReceiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewReceiverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewReceiverActionPerformed

    private void btnViewComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewComplaintActionPerformed
        // TODO add your handling code here:
        /*int selectedRow = TableComplaint.getSelectedRow();

        if (selectedRow >= 0)
        {
            Complaint s = (Complaint) TableComplaint.getValueAt(selectedRow, 0);
            //setvisable
            ComplaintNull.setVisible(false);
            ComplaintInformation.setVisible(true);

            //txt
            txtComAddresser.setText(s.getAddresser());
            txtComplaintEmployee.setText(s.getReceiver());
            txtComplaintReason.setText(s.getComplaintReason());
            txtComplaintDesc.setText(s.getDesc());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a school bus.");
        }*/
    }//GEN-LAST:event_btnViewComplaintActionPerformed

    private void sentMessageToAddresserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sentMessageToAddresserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sentMessageToAddresserActionPerformed

    private void btnphotoUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphotoUploadActionPerformed
        // TODO add your handling code here:
        /*JFileChooser upload = new JFileChooser();
        upload.showOpenDialog(null);
        File file = upload.getSelectedFile();
        String path = file.getAbsolutePath();
        imagePath = path;

        Image im = Toolkit.getDefaultToolkit().createImage(path);
        im = im.getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ima = new ImageIcon(im);
        kindergarden.setMyimage(ima);
        image.setIcon(ima);*/
    }//GEN-LAST:event_btnphotoUploadActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtName.setEnabled(true);
        txtEmail.setEnabled(true);
        txtDepartment.setEnabled(true);
        txtName.setEnabled(true);
      
        txtPassword.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnSave.setEnabled(true);
        btnphotoUpload.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        /*txtEntName.setText(kindergarden.getName());
        txtEntLocation.setText(kindergarden.getName());
        txtPhoneNumber.setText(kindergarden.getName());
        txtEntName.setText(kindergarden.getName());
        comboStatus.setSelectedItem(kindergarden.getStatus());
        comboxOpenTime.setSelectedItem(kindergarden.getOpenTime());
        comboxClosedTime.setSelectedItem(kindergarden.getClosedTime());*/
    }//GEN-LAST:event_btnSaveActionPerformed
    
    @Override
    public void run() {
        while (true) {            
            Calendar cal = Calendar.getInstance();
            hour = cal.get(Calendar.HOUR_OF_DAY);
            minute = cal.get(Calendar.MINUTE);
            second = cal.get(Calendar.SECOND);
            
            SimpleDateFormat sdftime = new SimpleDateFormat("yyyy-MM-dd  hh:mm:ss");
            Date date = cal.getTime();
            String timeForm = sdftime.format(date);
            labTime.setText(timeForm);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ComplaintInformation;
    private javax.swing.JPanel ComplaintJPanel;
    private javax.swing.JPanel ComplaintNull;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel IncidentReport;
    private javax.swing.JPanel ManageComplaint;
    private javax.swing.JPanel ManageInformation;
    private javax.swing.JPanel Patient;
    private javax.swing.JPanel PatientJPanel;
    private javax.swing.JPanel PatientNull;
    private javax.swing.JPanel PatientViewInformation;
    private javax.swing.JTable TableComplaint;
    private javax.swing.JTable TableNotification;
    private javax.swing.JTable TablePatient;
    private javax.swing.JTextArea TxtAreaDescription;
    private javax.swing.JTextArea TxtAreaExplanation;
    private javax.swing.JButton btnComplaint;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnInformation;
    private javax.swing.JButton btnLocation;
    private javax.swing.JButton btnMarkread;
    private javax.swing.JButton btnMyPatient;
    private javax.swing.JButton btnPatientSave;
    private javax.swing.JButton btnPatientUpload;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewBus1;
    private javax.swing.JButton btnViewComplaint;
    private javax.swing.JButton btnphotoUpload;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel labTime;
    private javax.swing.JLabel labelComplaintNum;
    private javax.swing.JLabel labelDoctorNum;
    private javax.swing.JLabel labelPatientNum;
    private javax.swing.JButton sentMessageToAddresser;
    private javax.swing.JTextField txtComAddresser;
    private javax.swing.JTextArea txtComplaintDesc;
    private javax.swing.JTextField txtComplaintReason;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPosition;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtUserAccount;
    private javax.swing.JTextField txtViewBus1;
    private javax.swing.JTextField txtViewReceiver;
    private javax.swing.JTextField vAdmissionTime;
    private javax.swing.JTextField vPatientName;
    private javax.swing.JTextField vPatientPhone;
    private javax.swing.JTextField vPatientTypeofillness;
    private javax.swing.JComboBox<String> vcomboxDegree;
    // End of variables declaration//GEN-END:variables
}
