/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.BookTickets;

import Business.Airliner;
import Business.AirlinerCatalog;
import Business.Airplane;
import Business.Business;
import Business.Customer;
import Business.Fleet;
import Business.Flight;
import Business.TicketCatalog;
import UserInterface.AirlinerRole.ManageAirplane;
import UserInterface.AirlinerRole.ManageTicket;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edmond
 */
public class SearchFlight extends javax.swing.JPanel {

    /**
     * Creates new form SearchFlight
     */
    private JPanel container;
    private AirlinerCatalog airlinerCatalog;
    private TicketCatalog ticketCatalog;
    private Customer customer;


    SearchFlight(JPanel Container, AirlinerCatalog ac, Customer c) {
        initComponents();
        container = Container;
        airlinerCatalog = ac;
        customer = c;
        refreshTable();
        Business business = new Business();
        this.ticketCatalog = business.getTicketCatalog();
    }

public void refreshTable(){
        
        DefaultTableModel model = (DefaultTableModel) tableFlight.getModel();
        model.setRowCount(0);
        
        for(Airliner al : airlinerCatalog.getAirlinerList()){
        for(Fleet a : al.getFleetCatalog().getFleetList()){
            for(Airplane ap: a.getAirplaneCatalog().getAirplaneCatalog()){
                for(Flight f : ap.getFlightCatalog().getFlightCatalog()){
                Object row[] = new Object[6];
                row[0] = f;
                row[1] = f.getDepartureLocation();
                row[2] = f.getArrivalLocation();
                row[3] = f.getDateofDay();
                row[4] = f.getTime();
                row[5] = f.count;
                model.addRow(row);
                
                    }
                }
            }
        }   
    }
    
  private void refreshFlightTable() {
        DefaultTableModel model = (DefaultTableModel) tableFlight.getModel();
        model.setRowCount(0);
        
        for(Airliner al : airlinerCatalog.getAirlinerList()){
        for(Fleet a : al.getFleetCatalog().getFleetList()){
            for(Airplane ap: a.getAirplaneCatalog().getAirplaneCatalog()){
                for(Flight f : ap.getFlightCatalog().getFlightCatalog()){             
                    boolean arrival = txtALocation.getText().equalsIgnoreCase(f.getArrivalLocation())||txtALocation.getText().equals("")||txtALocation.getText()==null;
                    System.out.println("81." + f.getArrivalLocation());
                    System.out.println("82." + txtALocation.getText());
                    System.out.println("searchFlight: 83." + arrival);
                    boolean day = f.getDateofDay().equalsIgnoreCase(txtDate.getText()) || txtDate.getText().equalsIgnoreCase("") || txtDate.getText()==null;
                    System.out.println("searchFlight: 85." + day);
                    boolean departure = f.getDepartureLocation().equalsIgnoreCase(txtDlocation.getText()) || txtDlocation.getText().equalsIgnoreCase("")|| txtDlocation.getText()==null;
                    System.out.println("searchFlight: 87." + departure);
                    boolean time = comboTime.getSelectedItem().equals(f.getTime()) || comboTime.getSelectedItem().equals("All");
                    System.out.println("searchFlight: 89." + time);
//                    System.out.println("searchFlight: 87." + arrival && day && departure && time);
                    if(arrival && day && departure && time){
                      Object row[] = new Object[5];
                      row[0] = f;
                      row[1] = f.getDepartureLocation();
                      row[2] = f.getArrivalLocation();
                      row[3] = f.getDateofDay();
                      row[4] = f.getTime();
                      model.addRow(row);  
                    } 
                    }
                }
            }
        }   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDlocation = new javax.swing.JTextField();
        txtALocation = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFlight = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboTime = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText("Search Flights");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("Depature Location:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("Date(DD/MM/YY):");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("Arrival Location:");

        txtDlocation.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtDlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDlocationActionPerformed(evt);
            }
        });

        txtALocation.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtALocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtALocationActionPerformed(evt);
            }
        });

        txtDate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        tableFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Departure Location", "Arrical Location", "Date", "Time", "Seating"
            }
        ));
        jScrollPane2.setViewportView(tableFlight);
        if (tableFlight.getColumnModel().getColumnCount() > 0) {
            tableFlight.getColumnModel().getColumn(0).setPreferredWidth(80);
            tableFlight.getColumnModel().getColumn(1).setPreferredWidth(125);
            tableFlight.getColumnModel().getColumn(2).setPreferredWidth(110);
        }

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnView.setText("View tickets of this flight >>");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setText("Time:");

        comboTime.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        comboTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Morning", "Noon", "Night" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDlocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txtALocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnBack)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtALocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnView)
                .addGap(38, 38, 38)
                .addComponent(btnBack)
                .addGap(116, 116, 116))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDlocationActionPerformed

    private void txtALocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtALocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtALocationActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component [] componentArray = container.getComponents();
        Component c = componentArray[componentArray.length-1];
        ManageCustomer m = (ManageCustomer) c;
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
//        txtDlocation.getText();
//        txtALocation.getText();
//        txtDate.getText();
        
        refreshFlightTable();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int row = tableFlight.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Flight a = (Flight) tableFlight.getValueAt(row,0);
        BookTickets ma = new BookTickets(container,a,ticketCatalog,customer);
        container.add("ManageTickets", ma);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> comboTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableFlight;
    private javax.swing.JTextField txtALocation;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDlocation;
    // End of variables declaration//GEN-END:variables

 
}
