/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Network.Network;
import Business.Resident.Resident;
import Business.Resident.ResidentDirectory;
import Business.Role.ResidentRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author edmond
 */
public class RegisterJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResisterJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public RegisterJPanel(JPanel userProcessContainer, EcoSystem ecoSystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        ecoSystem = dB4OUtil.retrieveSystem();
        
        RComboNetwork.removeAllItems();
        for(Network network : ecoSystem.getNetworkList()) {
            RComboNetwork.addItem(network);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtPhoneNum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        TXTEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labToLogin = new javax.swing.JLabel();
        fieldRePassword = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        RComboNetwork = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(58, 83, 155));
        jLabel7.setText("Network:");
        jLabel7.setToolTipText("");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, -1, 30));

        txtFullName.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtFullName.setToolTipText("");
        add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 180, 30));

        txtPhoneNum.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtPhoneNum.setToolTipText("");
        add(txtPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, 180, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(58, 83, 155));
        jLabel9.setText("SSN:");
        jLabel9.setToolTipText("");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, -1, 30));

        txtSSN.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtSSN.setToolTipText("");
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 180, 30));

        jPanel5.setBackground(new java.awt.Color(58, 83, 155));

        jLabel4.setBackground(new java.awt.Color(2, 2, 69));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome to Resident Registration");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(642, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(547, 547, 547))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(58, 83, 155));
        jLabel10.setText("User Name:");
        jLabel10.setToolTipText("");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, -1, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(58, 83, 155));
        jLabel14.setText("Phone Number:");
        jLabel14.setToolTipText("");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, 50));

        txtUserName.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtUserName.setToolTipText("");
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 180, 30));

        btnRegister.setBackground(new java.awt.Color(58, 83, 155));
        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 810, 130, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(58, 83, 155));
        jLabel11.setText("Password:");
        jLabel11.setToolTipText("");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, -1, 30));

        txtPassword.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        txtPassword.setToolTipText("");
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 610, 180, 30));

        TXTEmail.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        TXTEmail.setToolTipText("");
        add(TXTEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, 180, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(58, 83, 155));
        jLabel15.setText("Re-password:");
        jLabel15.setToolTipText("");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 680, -1, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(58, 83, 155));
        jLabel16.setText("E-mail:");
        jLabel16.setToolTipText("");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, -1, 30));

        labToLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labToLogin.setForeground(new java.awt.Color(58, 83, 155));
        labToLogin.setText("Click here to login.");
        labToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labToLoginMouseClicked(evt);
            }
        });
        add(labToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 920, -1, -1));

        fieldRePassword.setFont(new java.awt.Font("宋体", 0, 10)); // NOI18N
        add(fieldRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 690, 180, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(58, 83, 155));
        jLabel8.setText("Full Name:");
        jLabel8.setToolTipText("");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, 30));

        RComboNetwork.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RComboNetwork.setBorder(null);
        RComboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RComboNetworkActionPerformed(evt);
            }
        });
        add(RComboNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String fullname = txtFullName.getText();
        String ssn = txtSSN.getText();
        String email = TXTEmail.getText();
        String phoneNum = txtPhoneNum.getText();
        String username = txtUserName.getText();
        String password = txtPassword.getText();
        String networkName = RComboNetwork.getSelectedItem().toString();
        String repassword = String.valueOf(fieldRePassword.getPassword());
        if (repassword.equals(password)) {
            Employee employee = new Employee();
            employee.setId(ecoSystem.getResidentDirectory().getResidentAccountList().size()+1);
            employee.setName(fullname);
            if (ecoSystem.getResidentDirectory() == null){
                ecoSystem.setResidentDirectory(new ResidentDirectory());
            }
            ecoSystem.getResidentDirectory().createResidentAccount(username, password, employee, new ResidentRole());
            ecoSystem.getResidentDirectory().addResident(employee.getId(), networkName, fullname, ssn, email, phoneNum);
            
            JOptionPane.showMessageDialog(null, "Account created successfully!");
            dB4OUtil.storeSystem(ecoSystem);
            txtFullName.setText("");
            txtSSN.setText("");
            TXTEmail.setText("");
            txtPhoneNum.setText("");
            txtUserName.setText("");
            txtPassword.setText("");
            fieldRePassword.setText("");
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Your Password and Re-password should be consistent!");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void labToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labToLoginMouseClicked
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);       
    }//GEN-LAST:event_labToLoginMouseClicked

    private void RComboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RComboNetworkActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_RComboNetworkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox RComboNetwork;
    private javax.swing.JTextField TXTEmail;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPasswordField fieldRePassword;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labToLogin;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
